<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Assets\UI\FieldGuide\Pages\**" />
    <Compile Remove="Assets\UI\Settings\Buttons\**" />
    <EmbeddedResource Remove="Assets\UI\FieldGuide\Pages\**" />
    <EmbeddedResource Remove="Assets\UI\Settings\Buttons\**" />
    <Page Remove="Assets\UI\FieldGuide\Pages\**" />
    <Page Remove="Assets\UI\Settings\Buttons\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Config\creature_settings.json" />
    <None Remove="Config\point_of_interest_settings.json" />
    <None Remove="Screenshots\DesktopCreatures.gif" />
    <None Remove="Screenshots\DesktopCreatures2.gif" />
    <None Remove="Screenshots\RATS1.png" />
    <None Remove="Screenshots\RATS2.png" />
    <None Remove="Screenshots\RATS3.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="Config\debug_settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Config\creature_settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Config\point_of_interest_settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Config\app_settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Docs\Appearances_TODO.txt" />
    <Content Include="Docs\colors.txt" />
    <Content Include="Docs\regions.txt" />
    <Content Include="Screenshots\DesktopCreatures.gif">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Screenshots\DesktopCreatures2.gif">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Screenshots\RATS1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Screenshots\RATS2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Screenshots\RATS3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Creatures\Birds\Eagle\Appearance\Accessories\" />
    <Folder Include="Assets\Creatures\Birds\Eagle\Appearance\Appearances\" />
    <Folder Include="Assets\Creatures\Birds\Eagle\Appearance\Effects\" />
    <Folder Include="Assets\Creatures\Birds\Eagle\Appearance\Patterns\" />
    <Folder Include="Assets\Creatures\Birds\Eagle\Appearance\Palettes\" />
    <Folder Include="Assets\Creatures\Birds\Eagle\Sounds\" />
    <Folder Include="Assets\Creatures\Insects\Butterflies\" />
    <Folder Include="Assets\Creatures\Felines\Ocelot\Appearance\Accessories\" />
    <Folder Include="Assets\Creatures\Felines\Ocelot\Appearance\Effects\" />
    <Folder Include="Assets\Creatures\Felines\Ocelot\Appearance\Appearances\" />
    <Folder Include="Assets\Creatures\Felines\Ocelot\Appearance\Patterns\" />
    <Folder Include="Assets\Creatures\Felines\Ocelot\Sounds\" />
    <Folder Include="Assets\Creatures\Insects\" />
    <Folder Include="Assets\Items\" />
    <Folder Include="Assets\POI\WaterDish\" />
    <Folder Include="Assets\UI\FieldGuide\Sounds\" />
    <Folder Include="Graphics\Sprites\" />
    <Folder Include="Logs\" />
    <Folder Include="Persistence\Migrations\Legacy\" />
    <Folder Include="Rendering\Fonts\" />
    <Folder Include="UI\Controls\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PixelRecolor\PixelRecolor.Wpf\PixelRecolor.Wpf.csproj" />
    <ProjectReference Include="..\WpfBitmapFonts\WpfBitmapFonts.Core\WpfBitmapFonts.Core.csproj" />
  </ItemGroup>

</Project>